Fix a typo and update contributing.md
tensorchord/Awesome-LLMOps pull request #46
Opened 2023-04-22 15:21 UTC by hongshibao

2023-04-22 15:27 UTC, strickvl requested changes

2023-04-22 15:27 UTC, strickvl commented on contributing.md
> +    - Run `./scripts/generate-star-badges.py` to generate github star badges if needed.
```suggestion
    - Run `./scripts/generate-star-badges.py` to generate Github star badges if needed.
```

2023-04-22 16:15 UTC, strickvl approved these changes
Thanks for your contribution!

2023-04-23 01:57 UTC, merged

2023-04-23 01:57 UTC, gaocegege commented
Thanks for your contribution! :tada: :+1:

@strickvl Thanks for the review, I think you have the permission to merge.